
services:
  # app:
  #   container_name: snippet-api
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   image: snippet-api
  #   ports:
  #     - 8080:8080
  #   environment:
  #      - DB_HOST=mysql
  #      - DB_USER=snippet-admin
  #      - DB_PASSWORD=snippet-admin-password
  #      - DB_NAME=snippetBox
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #   # restart: unless-stopped
  #   networks: 
  #     - snippet-network
      
  mysql:
    container_name: snippet-db
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=snippet-admin
      - MYSQL_PASSWORD=snippet-admin-password
      - MYSQL_DATABASE=snippetBox
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - snippet-network
    healthcheck:
      test: ["CMD", "mysqladmin","ping", "-h","localhost"]
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  dbdata:

networks:
  snippet-network:
    driver: bridge